use company_db;

-- INSERT INTO department (name) VALUES ("Back Office");
-- INSERT INTO department (name) VALUES ("Software");
-- INSERT INTO department (name) VALUES ("Support");
-- INSERT INTO department (name) VALUES ("Kitchen");
INSERT INTO role (title, salary, dept_id) VALUES ("Overlord", 100000, 1);
INSERT INTO role (title, salary, dept_id) VALUES ("Boss", 150000, 1);
INSERT INTO role (title, salary, dept_id) VALUES ("Supervisor", 60000, 4);
INSERT INTO role (title, salary, dept_id) VALUES ("Dev 3", 100000, 2);
INSERT INTO role (title, salary, dept_id) VALUES ("Dev 1", 100000, 2);
INSERT INTO role (title, salary, dept_id) VALUES ("Admin Asst.", 50000, 3);
INSERT INTO role (title, salary, dept_id) VALUES ("Janitor", 35000, 3);
INSERT INTO role (title, salary, dept_id) VALUES ("Cook", 40000, 4);
INSERT INTO role (title, salary, dept_id) VALUES ("Scullery Maid", 45000, 4);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Mitch", "TheBitch", 1,1);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Sally", "Silly", 2, 1);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Fredrick", "FartFace", 3, 1);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Buster", "Brontosaurus", 4, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Sol", "Snake", 4, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Alice", "Aardvark", 5, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Kat", "Cat", 5, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Bob", "Burro", 5, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Dorris", "Donkey", 6, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Elaine", "Elephant", 6, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Frank", "Ferret", 7, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Gerry", "Gerbil", 7, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Harry", "Horse", 8, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Inga", "Iguana", 8, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Jerry", "Jackal", 8, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Keri", "Koala", 9, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Lenard", "Lemur", 9, 3);